#!/usr/bin/env ruby
#
# Compile the play itunes notification hook

# This script is called from the root of the project

class HookCompiler
  
  def initialize
    @compiler = "gcc"

    @source_dir = "depends/itunes_notification_hook"
    @source_file = "hook.m"

    @output_dir = "./bin"
    @output_name = "hook"
  end
  
  def compile
    puts `#{@compiler} #{@source_dir}/#{@source_file} -o #{@output_dir}/#{@output_name} -framework Cocoa`
    puts `chmod +x #{@output_dir}/#{@output_name}`
  end

  def clean
    `rm #{@output_dir}/#{@output_name}`
  end
end

compiler = HookCompiler.new

compiler.compile if ARGV[0] == "compile"
compiler.clean if ARGV[0] == "clean"